
targetContext: minikube

maintainers:
  - josdotso@cisco.com

team: product

apps:
  - name: hello
    alias: goodbye
    key: goodbye
    # Optionally, override appSources mechanism like this...
    #file: /tmp/hello.yaml
  - name: product

## For each app, the first appSource to find the app file exists as specified is selected.
## appSources are evaluated in the order declared here.
appSources:
  - name: apps
    kind: path
    source: ./apps
# - name: foo-deploy
#   kind: path
#   source: src/***REMOVED***/***REMOVED***/foo-deploy/multihelm/apps


imagePullPolicy: Always

goodbye:
  customValue: 100
