
targetContext: minikube

appsPath: ./apps

maintainers:
  - josdotso@cisco.com

team: product

apps:
  - name: hello
    alias: goodbye
    key: goodbye
  - name: product

imagePullPolicy: Always

goodbye:
  customValue: 100
