
targetContext: minikube

appsPath: ./apps

team: sre

maintainers:
  - josdotso@cisco.com

apps:
  - name: hello
    alias: hello-morning
    key: helloMorning
  - name: world

imagePullPolicy: Always

helloMorning:
  customValue: 42
